// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWech_K2bZBR9DPZAALDDfnxuKatcFm7M',
    appId: '1:121766014655:web:28277a83c2e40469aa200a',
    messagingSenderId: '121766014655',
    projectId: 'number-connection-rtes913',
    authDomain: 'number-connection-rtes913.firebaseapp.com',
    storageBucket: 'number-connection-rtes913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYh7nqewusIWA0pXLV26jZBOQ9SHc8MNg',
    appId: '1:121766014655:android:5fa05096dcfd442daa200a',
    messagingSenderId: '121766014655',
    projectId: 'number-connection-rtes913',
    storageBucket: 'number-connection-rtes913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRgyo3bpJbV7ChWEaRNjczab5olfxvgM',
    appId: '1:121766014655:ios:cf3d501bcbb5d83baa200a',
    messagingSenderId: '121766014655',
    projectId: 'number-connection-rtes913',
    storageBucket: 'number-connection-rtes913.appspot.com',
    iosBundleId: 'com.nycurtes.numberconnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRgyo3bpJbV7ChWEaRNjczab5olfxvgM',
    appId: '1:121766014655:ios:8e4ebd74f0e813b3aa200a',
    messagingSenderId: '121766014655',
    projectId: 'number-connection-rtes913',
    storageBucket: 'number-connection-rtes913.appspot.com',
    iosBundleId: 'com.example.numberConnectionTest.RunnerTests',
  );
}
